import { type ObjectModel } from '@stackbit/types';

export const sidebarAutoLinks: ObjectModel = {
	type: 'object',
	name: 'sidebarAutoLinks',
	label: 'Autogenerated Links',
	labelField: 'directory',
	fields: [
		{ name: 'directory', type: 'string' },
		{ name: 'collapsed', type: 'boolean' },
	],
};
