import { type ObjectModel } from '@stackbit/types';

export const sidebarAutoLinkGroup: ObjectModel = {
	type: 'object',
	name: 'sidebarAutoLinkGroup',
	label: 'Autogenerated Group of Links',
	labelField: 'label',
	fields: [
		{ name: 'label', type: 'string' },
		{
			name: 'autogenerate',
			type: 'model',
			models: ['sidebarAutoLinks'],
		},

		{ name: 'collapsed', type: 'boolean' },
	],
};
